# ============================================================
# HYPRLOCK
# Space Theme + #3297d3 Accent
# ============================================================


# -------------------- GENERAL --------------------

general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
}


# -------------------- BACKGROUND --------------------

background {
    monitor =
    path = screenshot

    blur_passes = 3
    blur_size = 5

    brightness = 0.60
    vibrancy = 0.15
    vibrancy_darkness = 0.0
}#----------------------- CLOCK --------------------

label {
    monitor =

    text = cmd[update:1000] echo "$(date +'%H:%M')"

    color = rgba(FFFFFFFF)

    font_size = 64
    font_family = JetBrainsMono Nerd Font
    font_weight = 700

    position = 0, 90

    halign = center
    valign = center
}


# -------------------- DATE --------------------

label {
    monitor =

    text = cmd[update:60000] echo "$(date +'%A %d %B')"

    color = rgba(FFFFFFFF)

    font_size = 15
    font_family = JetBrainsMono Nerd Font

    position = 0, 35

    halign = center
    valign = center
}


# -------------------- PASSWORD --------------------

input-field {
    monitor =

    size = 340, 54
    outline_thickness = 3

    dots_size = 0.20
    dots_spacing = 0.30
    dots_center = true

    # Main accent
    outer_color = rgb(3297d3)

    # Dark navy translucent background
    inner_color = rgba(24283BDD)

    font_color = rgb(FFFFFF)

    # Authentication colours
    check_color = rgb(3297d3)
    fail_color = rgb(FF5555)

    placeholder_text = <span foreground="##FFFFFF">Password</span>

    fade_on_empty = false
    hide_input = false

    rounding = 12

    position = 0, -50

    halign = center
    valign = center
}
